title: Engenharia Arquivei
description: > # this means to ignore newlines until "baseurl:"
  Somos a engenharia do Arquivei. Estamos aqui para compartilhar aprendizados no nosso caminho de construir a maior plataforma de dados financeiros do brasil
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://engenharia.arquivei.com.br" # the base hostname & protocol for your site, e.g. http://example.com

authors:
  arquivei:
    name: Arquivei
    image: arquivei.png
    about: Somos a engenharia do Arquivei. Estamos aqui para compartilhar aprendizados no nosso caminho de construir a maior plataforma de dados financeiros do brasil
    social_networks:
      facebook: arquivei
      github: arquivei
      twitter: arquiveioficial
      linkedin: company/4811635/
      email: engenharia@arquivei.com.br
  gustavo_san:
    name: Gustavo Santiago
    job: Frontend Intern
    image: gustavo_san.jpg
    about: Mah-oe do front-end. "Café, Techno e Lorem ipsum".
    social_networks:
      github: santiagogustavo
      linkedin: in/santiago-gustavo
      email: gustavo.santiago@arquivei.com.br
  leticia:
    name: Letícia Rostirola
    job: Quality Assurance
    image: leticia.jpg
    about: "QA walks into a bar. Orders a beer. Orders 999999999 beers. Orders a lizard."
    social_networks:
      github: ladylovelace
      twitter: lrostirola
      linkedin: in/lrostirola
      email: leticia.rostirola@arquivei.com.br
  olinda:
    name: Rafael Mariano
    job: Software Engineer
    image: olinda.jpg
    about: Sou fofurizator developer. "Javascript é funcional... o resto é gambiarra"
    social_networks:
      github: toruticas
      twitter: toruticas
      linkedin: in/toruticas
      email: rafael.silva@arquivei.com.br
  luccas:
    name: Luccas Rodrigues
    job: Software Reliability Engineer
    image: luccas.png
    about: Menino dos deploy. <br>"Fiz deploy, saí correndo..."
    social_networks:
      github: leluke
      linkedin: in/luccas-rodrigues-87497011b
      email: luccas.rodrigues@arquivei.com.br
  flipper:
    name: Vinicius Araujo
    job: Frontend Intern
    image: flipper.png
    about: Desenvolvedor aquático. <br>"Já ouviu falar em criptomoedas?"
    social_networks:
      facebook: vini.marchesin
      github: vmarchesin
      linkedin: in/vinicius-araujo-238a9b96/
      email: vinicius.araujo@arquivei.com.br
  leonardo_camargo:
    name: Leonardo Camargo
    job: Quality Assurance
    image: leonardo_camargo.jpg
    about: automaixo e otras cositas más. <br> "Numa escala de 0 a 10, 10".
    social_networks:
      facebook: leonardo.camargo.908
      github: leonardocamargo
      linkedin: in/leonardo-camargo-298286a0
      twitter: leocamargo1_
      email: lcamargo36@gmail.com
  edison_jr:
    name: Edison Silva Jr
    job: Software Engineer
    image: edison_jr.jpeg
    about: "Agora vai sobrar então, só um bugzinho pra cada sistema. Só um bugzinho. ;)"
    social_networks:
      github: esilvajr
      twitter: efrancsi
      linkedin: in/esilvajr
      email: edison.junior@arquivei.com.br
  andre_missaglia:
    name: André Badawi Missaglia
    job: Data Engineer
    image: missaglia.jpeg
    about: "Data is like people – interrogate it hard enough and it will tell you whatever you want to hear."
    social_networks:
      github: andremissaglia
      linkedin: in/andremissaglia
      email: andre.missaglia@arquivei.com.br
  barbie:
    name: Leonardo Miguel
    job: Data Engineer
    image: barbie.jpg
    about: "Usei usei eventos escrever para descrição es.sa"
    social_networks:
      github: leonardoam
      linkedin: in/leonardoalvesmiguel
      email: leonardo.miguel@arquivei.com.br
  victor_nunes:
    name: Victor Marcelino Nunes
    job: Software Engineer
    image: victor_nunes.jpg
    about: I would tell you a UDP joke <br> But you might not get it
    social_networks:
      facebook: vnunes9
      github: victormn
      twitter: victormn19
      linkedin: in/vmnunes
      email: victor.nunes@arquivei.com.br
  eduardo_soldera:
    name: Eduardo Soldera Garcia
    job: Data Engineer
    image: eduardo_soldera.png
    about: Re<strike>z</strike>solvedor de Problemas
    social_networks:
      linkedin: in/eduardosoldera
      email: eduardo.soldera@arquivei.com.br

# Disqus
discus-identifier: arquivei # add your discus identifier

# Tracker
analytics: UA-54265512-5 # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "docker-compose.yml"]
