title: Engenharia Arquivei
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

authors:
  arquivei:
    name: Arquivei
    image: arquivei.png
    about: Somos a engenharia do Arquivei. Estamos aqui para compartilhar aprendizados no nosso caminho de construir a maior plataforma de dados financeiros do brasil
    social_networks:
      facebook: arquivei
      github: arquivei
      twitter: arquiveioficial
      linkedin: company/4811635/
      email: engenharia@arquivei.com.br
  gustavo_san:
    name: Gustavo Santiago
    job: Frontend Intern
    image: gustavo_san.jpg
    about: Mah-oe do front-end. "Café, Techno e Lorem ipsum".
    social_networks:
      github: santiagogustavo
      linkedin: in/santiago-gustavo
      email: gustavo.santiago@arquivei.com.br
  olinda:
    name: Rafael Mariano
    job: Software Engineer
    image: olinda.jpg
    about: Sou fofurizator developer. "Javascript é funcional... o resto é gambiarra"
    social_networks:
      github: toruticas
      twitter: toruticas
      linkedin: in/toruticas
      email: rafael.silva@arquivei.com.br


# Disqus
discus-identifier: arquivei # add your discus identifier

# Tracker
analytics: UA-54265512-5 # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "docker-compose.yml"]
