title: Engenharia Arquivei
description: > # this means to ignore newlines until "baseurl:"
  Somos a engenharia do Arquivei. Estamos aqui para compartilhar aprendizados no nosso caminho de construir a maior plataforma de dados financeiros do brasil
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://engenharia.arquivei.com.br" # the base hostname & protocol for your site, e.g. http://example.com

authors:
  arquivei:
    name: Arquivei
    image: arquivei.png
    about: Somos a engenharia do Arquivei. Estamos aqui para compartilhar aprendizados no nosso caminho de construir a maior plataforma de dados financeiros do brasil
    social_networks:
      facebook: arquivei
      github: arquivei
      twitter: arquiveioficial
      linkedin: company/4811635/
      email: engenharia@arquivei.com.br
  gustavo_san:
    name: Gustavo Santiago
    job: Frontend Intern
    image: gustavo_san.jpg
    about: Mah-oe do front-end. "Café, Techno e Lorem ipsum".
    social_networks:
      github: santiagogustavo
      linkedin: in/santiago-gustavo
      email: gustavo.santiago@arquivei.com.br
  leticia:
    name: Letícia Rostirola
    job: Quality Assurance
    image: leticia.jpg
    about: "QA walks into a bar. Orders a beer. Orders 999999999 beers. Orders a lizard."
    social_networks:
      github: ladylovelace
      twitter: lrostirola
      linkedin: in/lrostirola
      email: leticia.rostirola@arquivei.com.br
  olinda:
    name: Rafael Mariano
    job: Software Engineer
    image: olinda.jpg
    about: Sou fofurizator developer. "Javascript é funcional... o resto é gambiarra"
    social_networks:
      github: leluke
      twitter: toruticas
      linkedin: in/toruticas
      email: rafael.silva@arquivei.com.br
  luccas:
    name: Luccas Rodrigues
    job: Software Reliability Engineer
    image: luccas.png
    about: Menino dos deploy. <br>"Fiz deploy, saí correndo..."
    social_networks:
      github: leluke
      linkedin: in/luccas-rodrigues-87497011b
      email: luccas.rodrigues@arquivei.com.br
  flipper:
    name: Vinicius Araujo
    job: Frontend Intern
    image: flipper.png
    about: Desenvolvedor aquático. <br>"Já ouviu falar em criptomoedas?"
    social_networks:
      facebook: vini.marchesin
      github: vmarchesin
      linkedin: in/vinicius-araujo-238a9b96/
      email: vinicius.araujo@arquivei.com.br

# Disqus
discus-identifier: arquivei # add your discus identifier

# Tracker
analytics: UA-54265512-5 # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "docker-compose.yml"]
